### ISSUE TITLE
Alsa crashes cpal when device is unavailable

### ISSUE THREAD

**Issue by jojolepro** [tomaka/cpal#208]
As said in title. I think the default behaviour should be to warn that no sound is going to be played as the device is unavailable. Current behaviour is panic.

The device not available error is normal. Alsa is configured to play on my headphones, which are not plugged in. I believe I should be able to run any app, even if the sound is not present. 

Might be a duplicate of #206, but the alsa returned error is not the same.

Backtrace: 
```
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

thread 'main' panicked at 'device not available: "Connection refused"', /checkout/src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:57
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:23
  10: <core::result::Result<T, E>>::expect
             at /checkout/src/libcore/result.rs:799
  11: cpal::cpal_impl::Endpoint::get_supported_formats_list
             at /home/jojolepro/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.4.6/src/alsa/mod.rs:87
  12: cpal::Endpoint::supported_formats
             at /home/jojolepro/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.4.6/src/lib.rs:156
  13: cpal::Endpoint::get_supported_formats_list
             at /home/jojolepro/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.4.6/src/lib.rs:165
  14: rodio::engine::new_voice
             at /home/jojolepro/.cargo/registry/src/github.com-1ecc6299db9ec823/rodio-0.5.2/src/engine.rs:106
  15: rodio::engine::Engine::start
             at /home/jojolepro/.cargo/registry/src/github.com-1ecc6299db9ec823/rodio-0.5.2/src/engine.rs:76
  16: rodio::engine::play_raw
             at /home/jojolepro/.cargo/registry/src/github.com-1ecc6299db9ec823/rodio-0.5.2/src/engine.rs:50
  17: rodio::sink::Sink::new
             at /home/jojolepro/.cargo/registry/src/github.com-1ecc6299db9ec823/rodio-0.5.2/src/sink.rs:37
  18: amethyst_audio::sink::AudioSink::new
             at amethyst_audio/src/sink.rs:18
```

**Comment by tomaka** [comment]
That's a rodio issue, not a cpal issue. Please reopen there!
