### ISSUE TITLE
Assertion failed: !buffer.is_null

### ISSUE THREAD

**Issue by SuperCuber** [tomaka/cpal#231]
Trying to run the example in the documentation for recording audio.

# Program
```rust
fn main() {
    // Setup the default input device and stream with the default input format.
    let device = cpal::default_input_device().expect("Failed to get default input device");
    println!("Default input device: {}", device.name());
    let format = device.default_input_format().expect("Failed to get default input format");
    println!("Default input format: {:?}", format);
    let event_loop = cpal::EventLoop::new();
    let stream_id = event_loop.build_input_stream(&device, &format).expect("Failed to build input stream");
    event_loop.play_stream(stream_id);
    event_loop.run(move |_, data| {
        if let cpal::StreamData::Input { buffer } = data {
            use cpal::UnknownTypeInputBuffer::*;
            match buffer {
               U16(buf) => println!("{:?}", &*buf),
               I16(buf) => println!("{:?}", &*buf),
               F32(buf) => println!("{:?}", &*buf),
            }
        }
    })
}
```

# Output
```
Default input device: Microphone (Logitech G430 Gaming Headset)
Default input format: Format { channels: 1, sample_rate: SampleRate(44100), data_type: F32 }
thread 'main' panicked at 'assertion failed: !buffer.is_null()', C:\Users\Glen\.cargo\registry\src\github.com-1ecc6299db9ec823\cpal-0.8.1\src\wasapi\stream.rs:523:29
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   2: std::sys_common::backtrace::print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:59
   3: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:211
   4: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:227
   5: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:463
   6: std::panicking::begin_panic<str*>
             at C:\projects\rust\src\libstd\panicking.rs:397
   7: cpal::cpal_impl::stream::EventLoop::run_inner
             at C:\Users\Glen\.cargo\registry\src\github.com-1ecc6299db9ec823\cpal-0.8.1\src\wasapi\stream.rs:523
   8: cpal::cpal_impl::stream::EventLoop::run<closure>
             at C:\Users\Glen\.cargo\registry\src\github.com-1ecc6299db9ec823\cpal-0.8.1\src\wasapi\stream.rs:423
   9: cpal::EventLoop::run<closure>
             at C:\Users\Glen\.cargo\registry\src\github.com-1ecc6299db9ec823\cpal-0.8.1\src\lib.rs:489
  10: antiscream::main
             at .\src\main.rs:100
  11: std::rt::lang_start::{{closure}}<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  12: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  13: std::panicking::try::do_call<closure,i32>
             at C:\projects\rust\src\libstd\panicking.rs:310
  14: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:105
  15: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  16: std::panic::catch_unwind
             at C:\projects\rust\src\libstd\panic.rs:374
  17: std::rt::lang_start_internal
             at C:\projects\rust\src\libstd\rt.rs:58
  18: std::rt::lang_start<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  19: main
  20: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:64
  21: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  22: BaseThreadInitThunk
  23: RtlUserThreadStart
```

Seems like the failed assertion is in [here](https://github.com/tomaka/cpal/blob/20fffb26fb9150ed8e1a19d3eafbf608dffa3480/src/wasapi/stream.rs#L523)

**Comment by SuperCuber** [comment]
@tomaka I see the project is still active, do you need additional information for this issue?

**Comment by LastExceed** [comment]
Fixed in the above linked PR
