### ISSUE TITLE
Segfault if delaying call to event_loop.run()

### ISSUE THREAD

**Issue by lgarczyn** [tomaka/cpal#254]
Running this simple code :

```
use std::io;

// Setup ports, and start threads
fn main() {
    // Setup the default input device and stream with the default input format.
    let device = cpal::default_input_device()
        .expect("Failed to get default input device");
    println!("Default input device: {}", device.name());

    // Get the default sound input format
    let format = device
        .default_input_format()
        .expect("Failed to get default input format");
    println!("Default input format: {:?}", format);

    // Start the cpal input stream
    let event_loop = cpal::EventLoop::new();
    let stream_id = event_loop
        .build_input_stream(&device, &format)
        .expect("Failed to build input stream");
    event_loop.play_stream(stream_id);

    // Await user input
    println!("Press enter/return to start reading frequencies ...");
    let mut user_input = String::new();
    io::stdin().read_line(&mut user_input).ok();

    // Spawn the audio input reading thread
    std::thread::spawn(move || {
        event_loop.run(move |_, _| {});
    });

    // Wait for user input to quit
    println!("Press enter/return to quit...");
    let mut user_input = String::new();
    io::stdin().read_line(&mut user_input).ok();
}
```

with the output:

```
  Compiling improve v0.1.0 (/home/lgarczyn/Projects/improve)
    Finished dev [unoptimized + debuginfo] target(s) in 0.47s
     Running `target/debug/improve`
Default input device: "default"
Default input format: Format { channels: 2, sample_rate: SampleRate(44100), data_type: F32 }
Press enter/return to start reading frequencies ...

Press enter/return to quit...
double free or corruption (!prev)
[1]    17669 segmentation fault (core dumped)  cargo run`
```
The code doesn't crash on MacOS, and if I remove the "Await user input" lines, the code works fine. 
I'm using Linux Mint, using both Alsa and Pulseaudio

**Comment by lgarczyn** [comment]
Other bugs I've experienced on the same configuration:

* random segfault if I leave the program running long enough, but not every time

* panic when reading the name of the third input device :
```
    println!("devices: {}", cpal::input_devices().skip(2).take(3).map(|d| d.name()).join(", "));
```
displays:
```
ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_dmix.c:990:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:990:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
thread 'main' panicked at 'device not available: "Invalid argument"', src/libcore/result.rs:999:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/c2d381d39d282c0586d50ea7d7a431ffd5ddb3fb/src/libcore/macros.rs:16
   9: <core::result::Result<T, E>>::expect
             at /rustc/c2d381d39d282c0586d50ea7d7a431ffd5ddb3fb/src/libcore/result.rs:825
  10: cpal::cpal_impl::Device::supported_formats
             at /home/lgarczyn/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.8.2/src/alsa/mod.rs:95
  11: cpal::cpal_impl::Device::supported_input_formats
             at /home/lgarczyn/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.8.2/src/alsa/mod.rs:252
  12: cpal::Device::supported_input_formats
             at /home/lgarczyn/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.8.2/src/lib.rs:374
  13: cpal::input_devices::supports_input
             at /home/lgarczyn/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.8.2/src/lib.rs:328
  14: core::ops::function::FnMut::call_mut
             at /rustc/c2d381d39d282c0586d50ea7d7a431ffd5ddb3fb/src/libcore/ops/function.rs:148
  15: <core::iter::Filter<I, P> as core::iter::iterator::Iterator>::next
             at /rustc/c2d381d39d282c0586d50ea7d7a431ffd5ddb3fb/src/libcore/iter/mod.rs:1538
  16: <&mut I as core::iter::iterator::Iterator>::next
             at /rustc/c2d381d39d282c0586d50ea7d7a431ffd5ddb3fb/src/libcore/iter/iterator.rs:2644
  17: core::iter::iterator::Iterator::nth
             at /rustc/c2d381d39d282c0586d50ea7d7a431ffd5ddb3fb/src/libcore/iter/iterator.rs:316
  18: <core::iter::Skip<I> as core::iter::iterator::Iterator>::next
             at /rustc/c2d381d39d282c0586d50ea7d7a431ffd5ddb3fb/src/libcore/iter/mod.rs:2254
  19: <core::iter::Take<I> as core::iter::iterator::Iterator>::next
             at /rustc/c2d381d39d282c0586d50ea7d7a431ffd5ddb3fb/src/libcore/iter/mod.rs:2389
  20: <core::iter::Map<I, F> as core::iter::iterator::Iterator>::next
             at /rustc/c2d381d39d282c0586d50ea7d7a431ffd5ddb3fb/src/libcore/iter/mod.rs:1426
  21: itertools::Itertools::join
             at /home/lgarczyn/.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.8.0/src/lib.rs:1464
  22: improve::main
             at src/main.rs:73
  23: std::rt::lang_start::{{closure}}
             at /rustc/c2d381d39d282c0586d50ea7d7a431ffd5ddb3fb/src/libstd/rt.rs:64
  24: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  25: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:92
  26: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  27: std::rt::lang_start
             at /rustc/c2d381d39d282c0586d50ea7d7a431ffd5ddb3fb/src/libstd/rt.rs:64
  28: main
  29: __libc_start_main
  30: _start

```

**Comment by MOZGIII** [comment]
It crashes for me too. I think the issue is within the alsa mod, somewhere in here:
https://github.com/tomaka/cpal/blob/c2d606176a88ae9610e2b7f17b844f04eccd320e/src/alsa/mod.rs#L547-L568

**Comment by MOZGIII** [comment]
I bet the problem is with uninitialized memory: https://github.com/tomaka/cpal/blob/2679ea845fe0460e1514d9f63c7c8048525e306b/src/alsa/mod.rs#L550-L552

**Comment by MOZGIII** [comment]
I tried this a different distribution (Gentoo), and the problem does not appear there. This makes me thing there's an issue with the system, rather than the cpal. For my case, of course.
Some details on my system where the bug reproduces: Ubuntu 18.04; PulseAudio, udev and pretty much everything else involved are from standard distro packages.

**Comment by mitchmindtree** [comment]
#254 supposedly closes this but I haven't tested this to be sure.

Please let me know if the error is still occurring and I'll be happy to re-open the issue!

**Comment by MOZGIII** [comment]
I'll test it asap, thx. What's the idea behind the fix?

**Comment by mitchmindtree** [comment]
It fixes a case where a value used for available *samples* was incorrectly used instead of available *frames* in the ALSA backend. It also initialises buffers to be zeroed before use.

**Comment by MOZGIII** [comment]
Oh, yeah, that was unfortunate. I overlooked this when I was reviewing the code myself. it looks like the code works now.
It seems to work great! I'll give it a few more hours and see if it crashes, but it look very much like the root cause of the crash was fixed.

Btw, I'm not sure if not zero-initializing the memory gives the performance betefit, but we might revert back to using uninitialized memory there - even though I suspected that was the cause of the crash in my further tests I concluded that it's not (I basicly replaced the uninitialized allocation with zero-initialized allocation and the result was the same). So, should we consider switching back to allocating unitiialized memory?

**Comment by ishitatsuyuki** [comment]
Zero-initializing was just for a bonus - it's more idiomatic, the `vec!` sugar makes it shorter, and as getting tested for other projects it made no performance difference (the nature of `calloc` makes it efficient).

**Comment by MOZGIII** [comment]
Great, I feel much better now knowing there's no uninitialized allocations at ALSA *and* there's no performance penalty for it.

Speaking of performance - it might be a good idea to reuse buffers instead of allocating them on each iteration. (This is just a side note, as it's not really relevant for this issue.) It seems to be a quite useless allocator pressure. Though, it works for me so far.
