### ISSUE TITLE
beep crashes on mipsel alsa target

### ISSUE THREAD

**Issue by psych0d0g** [tomaka/cpal#97]
./beep 

> thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "Invalid argument"', ../src/libcore/result.rs:688

**Comment by psych0d0g** [comment]
even after compiling beep with #98 applied the error message stays the same

**Comment by tomaka** [comment]
Could you get a backtrace with `RUST_BACKTRACE=1`?

**Comment by psych0d0g** [comment]
sure: thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "Invalid argument"', ../src/libcore/result.rs:688
stack backtrace:
   1: 0x76fe440f - sys::backtrace::tracing::imp::write::hb0563fd8feed89728eu
   2: 0x76fe714b - panicking::default_handler::_<closure>::closure.42583
   3: 0x76fe6a8f - panicking::default_handler::hbd850397f6692201asy
   4: 0x76fde4eb - sys_common::unwind::begin_unwind_inner::hfc80d8dae0ea58e6F7s
   5: 0x76fde7c3 - sys_common::unwind::begin_unwind_fmt::h9de7c0ab9b6ac79cL6s
   6: 0x76fe35b3 - rust_begin_unwind
   7: 0x7702951f - panicking::panic_fmt::h1f8334a13f44d76dFVL
   8: 0x76fdc837 - cpal_impl::Voice::new::hffff16cde5875bf1uBa
   9: 0x76fc8daf - Voice::new::h48a7e3732508b6a1Ynb
  10: 0x76fc2f53 - main::hafa0319baba5c8bcfaa
  11: 0x76fe656b - sys_common::unwind::try::try_fn::h12180153579636997735
  12: 0x76fe34ef - __rust_try
  13: 0x76fe617f - rt::lang_start::h96ede41baee7c740oky
  14: 0x76fda04f - main
  15: 0x76cca003 - <unknown>

**Comment by tomaka** [comment]
Thanks.
It's probably one of these: https://github.com/tomaka/cpal/blob/master/src/alsa/mod.rs#L231-L238

The `unwrap()`s should be replaced by `expect()` so that we can know where the problem comes from.
It's late for me here so I won't do it today, but you can do it if you're motivated!

**Comment by psych0d0g** [comment]
with debug info:

```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "Invalid argument"', ../src/libcore/result.rs:688
stack backtrace:
   1: 0x771c6a93 - sys::backtrace::tracing::imp::write::hb0563fd8feed89728eu
   2: 0x771c97cf - panicking::default_handler::_<closure>::closure.42583
   3: 0x771c9113 - panicking::default_handler::hbd850397f6692201asy
   4: 0x771c0b6f - sys_common::unwind::begin_unwind_inner::hfc80d8dae0ea58e6F7s
   5: 0x771c0e47 - sys_common::unwind::begin_unwind_fmt::h9de7c0ab9b6ac79cL6s
   6: 0x771c5c37 - rust_begin_unwind
   7: 0x7720bb9f - panicking::panic_fmt::h1f8334a13f44d76dFVL
   8: 0x771beebb - cpal_impl::Voice::new::hffff16cde5875bf1uBa
   9: 0x771a95ef - Voice::new::h48a7e3732508b6a1Ynb
                at src/lib.rs:286
  10: 0x771a2f9b - main::hafa0319baba5c8bcfaa
                at examples/beep.rs:6
  11: 0x771c8bef - sys_common::unwind::try::try_fn::h12180153579636997735
  12: 0x771c5b73 - __rust_try
  13: 0x771c8803 - rt::lang_start::h96ede41baee7c740oky
  14: 0x771bc6d3 - main
  15: 0x76eaa003 - <unknown>
```

**Comment by psych0d0g** [comment]
and with added expect's:

```
thread '<main>' panicked at 'hardware params could not be set: "Invalid argument"', ../src/libcore/result.rs:709
stack backtrace:
   1: 0x77773f83 - sys::backtrace::tracing::imp::write::hb0563fd8feed89728eu
   2: 0x77776cbf - panicking::default_handler::_<closure>::closure.42583
   3: 0x77776603 - panicking::default_handler::hbd850397f6692201asy
   4: 0x7776e05f - sys_common::unwind::begin_unwind_inner::hfc80d8dae0ea58e6F7s
   5: 0x7776e337 - sys_common::unwind::begin_unwind_fmt::h9de7c0ab9b6ac79cL6s
   6: 0x77773127 - rust_begin_unwind
   7: 0x777b908f - panicking::panic_fmt::h1f8334a13f44d76dFVL
   8: 0x7775f24f - result::Result<T, E>::expect::h15371475496069994930
                at ../src/libcore/macros.rs:29
   9: 0x7775e56f - cpal_impl::Voice::new::h9b4d5d18d0730c92BBa
                at src/alsa/mod.rs:236
  10: 0x7774473f - Voice::new::ha31f8d5e31ae6715oob
                at src/lib.rs:286
  11: 0x7773e07b - main::hafa0319baba5c8bcfaa
                at examples/beep.rs:6
  12: 0x777760df - sys_common::unwind::try::try_fn::h12180153579636997735
  13: 0x77773063 - __rust_try
  14: 0x77775cf3 - rt::lang_start::h96ede41baee7c740oky
  15: 0x777579b3 - main
  16: 0x77442003 - <unknown>
```

**Comment by psych0d0g** [comment]
output of enumerate:
https://gist.github.com/psych0d0g/0c00ddf99b26500ebded
output of aplay -l:
**** List of PLAYBACK Hardware Devices ****
card 0: VuPlus [], device 0: BCM7xxx [BCM7xxx]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

**Comment by tomaka** [comment]
The only problem I see is that cpal assumes that interleaved samples are supported.

You could try replacing `SND_PCM_ACCESS_RW_INTERLEAVED` with `SND_PCM_ACCESS_RW_NONINTERLEAVED` and see if there's still an error.

**Comment by mitchmindtree** [comment]
Closing this due to inactivity and seeing as the ALSA backend has gone through multiple refactorings since this that may have addressed the original issue. Please feel free to re-open if this is still occurring!
